### ISSUE TITLE
Address did:peer:2 spec changes

### ISSUE THREAD

**Issue by goncalo-frade-iohk** [beatt83/peerdid-swift#1]
Address the following changes reported on this ticket:

https://github.com/decentralized-identity/peer-did-method-spec/issues/64

**Comment by FabioPinheiro** [comment]
Isn't this Done in your lib? or is it in another repository?

**Comment by beatt83** [comment]
Here is the fix for this.

https://github.com/beatt83/peerdid-swift/pull/2

**Comment by beatt83** [comment]
Here is the second PR for the fix of the services:

https://github.com/beatt83/peerdid-swift/pull/3

**Comment by beatt83** [comment]
They are both merged. I close this issue :)
